// KiwiSaver Fund Finder — Frontend Logic

const fundData = []; // Populated from CSV/JSON

// Goal selections
function selectGoal(goal) {
    sessionStorage.setItem('ks-goal', goal);
    document.getElementById('step-type').classList.remove('hidden');
    window.scrollTo(0, document.getElementById('step-type').offsetTop - 20);
}

function selectType(type) {
    sessionStorage.setItem('ks-type', type);
    document.getElementById('step-age').classList.remove('hidden');
    window.scrollTo(0, document.getElementById('step-age').offsetTop - 20);
}

function showResults() {
    const age = document.getElementById('age').value;
    const goal = sessionStorage.getItem('ks-goal');
    const type = sessionStorage.getItem('ks-type');
    
    if (!age) {
        alert('Please enter your age');
        return;
    }
    
    sessionStorage.setItem('ks-age', age);
    document.getElementById('results').classList.remove('hidden');
    
    renderResults(age, goal, type);
    window.scrollTo(0, document.getElementById('results').offsetTop - 20);
}

// Load fund data from JSON (generated by analysis script)
async function loadFundData() {
    try {
        const response = await fetch('data/funds.json');
        if (response.ok) {
            const data = await response.json();
            fundData.splice(0, 0, ...data);
        }
    } catch (e) {
        console.log('Fund data not yet available — early development');
    }
}

function classifyAge(age) {
    // Infer fund type from age if user doesn't know
    age = parseInt(age);
    if (age < 35) return 'aggressive';
    if (age < 50) return 'growth';
    if (age < 60) return 'balanced';
    return 'moderate';
}

function renderResults(age, goal, type) {
    const recList = document.getElementById('recommended-list');
    const avoidList = document.getElementById('avoid-list');
    
    // If type unknown, infer from age
    let effectiveType = type === 'unknown' ? classifyAge(age) : type;
    
    // For demo: show placeholder cards based on type
    // In production: filter from actual fundData
    
    let recHTML = '<div class="rec-section">';
    recHTML += '<h3>✅ Recommended <span class="count">2</span></h3>';
    recHTML += buildFundCard({
        name: 'Simplicity Growth Fund',
        scheme: 'Simplicity',
        type: effectiveType,
        fee: '0.10%',
        return5yr: '+8.2%',
        benchmark: '+8.1%',
        recommendation: 'recommended',
        feeImpact: '$47,000',
        currency: 'Unhedged',
        geo: '55% Global · 25% AUS · 20% NZ'
    });
    recHTML += buildFundCard({
        name: 'Kernel Global 100 Fund',
        scheme: 'Kernel',
        type: 'total-equities',
        fee: '0.20%',
        return5yr: '+8.4%',
        benchmark: '+8.2%',
        recommendation: 'recommended',
        feeImpact: '$38,000',
        currency: 'Unhedged',
        geo: '100% Global'
    });
    recHTML += '</div>';
    
    let avoidHTML = '<div class="rec-section">';
    avoidHTML += '<h3>❌ Avoid <span class="count">3</span></h3>';
    avoidHTML += buildFundCard({
        name: 'Example Active Growth Fund',
        scheme: 'Some Provider',
        type: 'growth',
        fee: '1.35%',
        return5yr: '+5.8%',
        benchmark: '+8.1%',
        recommendation: 'avoid',
        feeImpact: '$142,000',
        currency: 'Hedged',
        geo: '45% NZ · 30% AUS · 25% Global',
        reasons: ['Fees 1.35% — passive alternative at 0.2%', 'Underperformed benchmark 3.2% over 5 years', 'Active management adds no value here']
    });
    avoidHTML += '</div>';
    
    recList.innerHTML = recHTML;
    avoidList.innerHTML = avoidHTML;
}

function buildFundCard(fund) {
    const statusClass = fund.recommendation;
    const feeClass = parseFloat(fund.fee) > 0.7 ? 'high' : 'low';
    
    let reasonsHTML = '';
    if (fund.reasons) {
        reasonsHTML = '<div style="margin-top:8px;">';
        fund.reasons.forEach(r => {
            reasonsHTML += `<div style="font-size:0.82rem;color:#c0392b;">⚠️ ${r}</div>`;
        });
        reasonsHTML += '</div>';
    }
    
    return `
    <div class="fund-card ${statusClass}">
        <div class="fund-info">
            <h4>${fund.name}</h4>
            <div class="scheme">${fund.scheme}</div>
            <div class="fund-meta">
                <span>${fund.geo}</span>
                <span>${fund.currency}</span>
                <span>Passive</span>
            </div>
            ${reasonsHTML}
        </div>
        <div class="fund-stats">
            <div class="fee ${feeClass}">${fund.fee} fees</div>
            <div class="returns">5yr: ${fund.return5yr} (bench ${fund.benchmark})</div>
            ${fund.feeImpact ? `<div class="fee-impact">Costs ${fund.feeImpact} more vs passive over 30yr</div>` : ''}
        </div>
    </div>`;
}

// Load on startup
loadFundData();
